# Generated by Django 5.2.1 on 2025-06-05 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='retailer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_bsp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_app_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
