# Generated by Django 5.2.1 on 2025-06-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='whatsapp_app_id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='whatsapp_bsp_api_key',
        ),
    ]
