# Generated by Django 5.2.1 on 2025-06-11 06:06

from django.db import migrations
from django.conf import settings # We'll get user model from settings
import os # To get environment variables

def create_superuser(apps, schema_editor):
    """
    Creates a superuser if one does not exist, using credentials
    from environment variables.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    SU_USERNAME = os.environ.get('DJANGO_SU_NAME')
    SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    if SU_USERNAME and SU_EMAIL and SU_PASSWORD:
        if not User.objects.filter(username=SU_USERNAME).exists():
            print(f"\nCreating superuser: {SU_USERNAME}")
            User.objects.create_superuser(
                username=SU_USERNAME,
                email=SU_EMAIL,
                password=SU_PASSWORD
            )
        else:
            print(f"\nSuperuser {SU_USERNAME} already exists. Skipping.")
    else:
        print("\nSuperuser credentials (DJANGO_SU_NAME, DJANGO_SU_EMAIL, DJANGO_SU_PASSWORD) not found in environment. Skipping.")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
