# Generated by Django 5.2.1 on 2025-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_comms', '0002_alter_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('STARTED', 'Started'), ('AWAITING_PRODUCT_QUERY', 'Awaiting Product Query')], default='STARTED', max_length=30),
        ),
    ]
