# Generated by Django 5.2.1 on 2025-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_comms', '0004_alter_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('STARTED', 'Started'), ('AWAITING_COMMAND', 'Awaiting Command'), ('AWAITING_PRODUCT_SELECTION', 'Awaiting Product Selection'), ('AWAITING_PRODUCT_ACTION', 'Awaiting Product Action'), ('AWAITING_SIZE_SELECTION', 'Awaiting Size Selection'), ('AWAITING_QUANTITY', 'Awaiting Quantity')], default='STARTED', max_length=30),
        ),
    ]
