# Generated by Django 5.2.1 on 2025-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_comms', '0005_alter_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('STARTED', 'Started'), ('AWAITING_COMMAND', 'Awaiting Command'), ('AWAITING_PRODUCT_SELECTION', 'Awaiting Product Selection'), ('AWAITING_PRODUCT_ACTION', 'Awaiting Product Action'), ('AWAITING_SIZE_SELECTION', 'Awaiting Size Selection'), ('AWAITING_QUANTITY', 'Awaiting Quantity'), ('VIEWING_CART', 'Viewing Cart'), ('AWAITING_DELIVERY_CHOICE', 'Awaiting Delivery Choice'), ('AWAITING_DELIVERY_ADDRESS', 'Awaiting Delivery Address'), ('AWAITING_PAYMENT_CONFIRMATION', 'Awaiting Payment Confirmation')], default='STARTED', max_length=30),
        ),
    ]
