# Generated by Django 5.2.1 on 2025-06-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sellers', '0003_remove_sellerprofile_whatsapp_app_id_and_more'),
        ('whatsapp_comms', '0003_alter_conversation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress (Cart)'), ('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_APPROVAL', 'Pending Approval'), ('PROCESSING', 'Processing'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_option', models.CharField(blank=True, choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=10, null=True)),
                ('delivery_address_text', models.TextField(blank=True, null=True)),
                ('delivery_location_coordinates', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='whatsapp_comms.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sellers.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time_of_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
